### ISSUE TITLE
Adding calculator to your favorite list

### ISSUE THREAD

**Issue by nipun221** [SarthakKeshari/calc_for_everything#298]
**Is your feature request related to a problem? Please describe.**
Creating a bucket that stores the favorite calculators of the user and that can be displayed separately.

**Describe the solution you'd like**
Cookies should be used to store the list data of favorite items(calculators).

**Describe alternatives you've considered**
Local storage can be used as a temporary solution. 

**Additional context**

**Comment by nipun221** [comment]
@SarthakKeshari  Kindly assign me this issue.

**Comment by SarthakKeshari** [comment]
Hey @nipun221,
Assigned.

#### Be careful, do not break the old code that already exists.

Issue completion deadline - 19th Oct 4:00:00 pm IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by sikehish** [comment]
Could you brief me about the issue? It lacks clarity

**Comment by SarthakKeshari** [comment]
@sikehish,
The issue requires user to be able to add his frequently used calculators to a favourite list.

**Comment by sikehish** [comment]
I'm interested in working on this

**Comment by SarthakKeshari** [comment]
Hey @sikehish,
Assigned.

#### Be careful, do not break the old code that already exists.

Issue completion deadline - 24th Oct 12:00:00 noon IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by sikehish** [comment]
@SarthakKeshari Hi Sarthak. Ive spent quite some time on it, and Ive realized that this cannot be accomplished without creating arrays for each of the 8 categories of calculators, with each arrays consisting of objects of the type: {calcName, path}. As the values are hardcoded, it cannot be done.

**Comment by SarthakKeshari** [comment]
@sikehish,
I understand, there are couple of changes that will be required which will impact the project as a whole as well. Since the Hacktoberfest for this year is going for a sunset in next 7 days. I won't prefer taking this issue up. As many contributors are new to the platform (Github) and might face challenges in-case something breaks. I believe in taking up Hacktoberfest as a chance for providing a learning opportunity for all contributors, so I do not want to affect their learning. 

Will be unassigning and closing this issue. You may re-open it after October if you which to implement it. And I will provide you the chance to add the favorites feature in a way that you find is the best fit for this project.

**Comment by sikehish** [comment]
Hi @SarthakKeshari . Thanks for the opportunity! That's a sensible move. I'll try to contribute post hacktoberfest!
