### ISSUE TITLE
feat: Husky Prettier Eslint - for CodeBase Improvement.

### ISSUE THREAD

**Issue by Tholkappiar** [SarthakKeshari/calc_for_everything#536]
**Is your feature request related to a problem? Please describe.**
No its is not a problem , but when more number of people are contributing to the repo , the codebase will not look similar cause who are contributing to the repository have their own way of styling their code . When new persons try to contribute they will see the uneven stylings ( like spaces ..etc ...)

**Describe the solution you'd like**
The solution in simple whenever contributors commit the code , the code will be automatically changed and formatted to a standard professional format . By doing this , the Code Base format will become standard .

**Describe alternatives you've considered**
Nothing , this is the best way . Many repository use this method to maintain the format and also this simplifies the work !

**Additional context**
_This is an example SS after committing the code :_ 

![code-enhance](https://github.com/SarthakKeshari/calc_for_everything/assets/114584730/64fa6b3e-44e0-45eb-89e7-d8d3247b454b)

_PS :_ **I'm eager to work on this. Please assign this issue to me.**

**Comment by SarthakKeshari** [comment]
@Tholkappiar,
I understand, there are couple of changes that will be required which will impact the project as a whole as well. Since the Hacktoberfest for this year is going for a sunset in next 2 days. I won't prefer taking this issue up, as many contributors are new to the platform (Github) and might face challenges in-case something breaks. I believe in taking up Hacktoberfest as a chance for providing a learning opportunity for all contributors, so I do not want to affect their learning.

Will be closing this issue. You may re-open it after October if you wish to implement it. And I will provide you the chance to add this improvement in a way that you find is the best fit for this project.
